- name: exec docker script
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker.io
    - docker-compose
  notify: install docker compose

  
- name: install docker compose
  pip:
    name:
      - docker
      - docker-compose
    state: forcereinstall