version: "3.9"

services:
  app:
    image: tcl-docker-test
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    profiles:
      - app_too
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:13.2
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres-volume:/var/lib/postgresql/
    profiles:
      - main
      - app_too
  redis:
    image: redis
    restart: always
    ports:
      - "6388:6388"
    expose:
      - 6388
    volumes:
      - redis_volume:/data
    entrypoint: redis-server --appendonly yes --port 6388
    profiles:
      - main
      - app_too

volumes:
  postgres-volume:
  redis-volume: