- name: docker-compose start celery worker
  shell: docker-compose -f /var/www/app/docker-compose.prod.yaml --profile worker up -d --force-recreate 
  timeout: 300 # 5 minutes

- name: docker-compose force rebuild celery worker
  shell: |
    cd /var/www/app/
    docker-compose -f docker-compose.prod.yaml --profile worker stop
    docker-compose rm -f
    docker-compose pull   
    docker-compose -f docker-compose.prod.yaml --profile worker up -d --force-recreate